from enum import Enum

class Layer(Enum):
    ARGMAX 
    AVERAGEPOOLING
    BATCHNORMALIZATION 
    CONV1D
    CONV2D 
    DENSE
    FLATTEN2D
    GLOBALAVERAGEPOOLING
    GLOBALMAXPOOLING
    GLOBALSUMPOOLING
    POLY
    RELU
    SUMPOOLING